Copaces.CityCounty.Website/Controllers/RoadsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Copaces.CityCounty.Website.Models;
using Copaces.CityCounty.Website.Models.DataObjects;
using Copaces.CityCounty.Website.Utility;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;



namespace Copaces.CityCounty.Website.Controllers
{
    public class RoadsController : Controller
    {
        /// <summary>
        /// Application DB context
        /// </summary>
        ApplicationDbContext ApplicationDbContext { get; set; }

        /// <summary>
        /// User manager - attached to application DB context
        /// </summary>
        UserManager<ApplicationUser> UserManager { get; set; }

        public RoadsController()
        {
            ApplicationDbContext = new ApplicationDbContext();
            UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        // GET: Roads/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create(
        //    [Bind(
        //        Include =
        //            "Id,BridgeNum,BridgeWidth,CulvertAndPipeNum,District,From,FunctionalClass,HasUnfinishedSurvey,Jurisdiction,LaneNum,LastSurveyDate,Name,PavMarkingCondition,PavWidthMax,PavWidthMin,PavWidthTypical,PlaceId,PlaceType,Remarks,ShoulderWidthMax,ShoulderWidthMin,ShoulderWidthTypical,SurfaceType,To,UnpavedShoulderWidth"
        //        )] Road road)
        //{
        public async Task<ActionResult> Create(
           [Bind(
               Include =
                   "BridgeNum,BridgeWidth,CulvertAndPipeNum,District,From,FunctionalClass,HasUnfinishedSurvey,LaneNum,LastSurveyDate,Name,PavMarkingCondition,PavWidthMax,PavWidthMin,PavWidthTypical,PlaceType,Remarks,ShoulderWidthMax,ShoulderWidthMin,ShoulderWidthTypical,SurfaceType,To,UnpavedShoulderWidth"
               )] Road road)
        {
            if (ModelState.IsValid)
            {
                //db.Roads.Add(road);
                //await db.SaveChangesAsync();
                var curUser = UserManager.FindById(User.Identity.GetUserId());
                road.Jurisdiction = curUser.PlaceName;
                road.PlaceType = ApiHelper.GetPlaceById(curUser.PlaceId).Result.Type;
                road.Id = ApiHelper.GetNextRoadId();
                road.PlaceId = curUser.PlaceId;
                await ApiHelper.CreateRoad(road);
                return RedirectToAction("Index");
            }

            return View(road);
        }



        // GET: Roads/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var road = await ApiHelper.GetRoadById(id);
            if (road == null)
            {
                return HttpNotFound();
            }
            return View(road);
        }

        // POST: Roads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            //var road = await db.Roads.FindAsync(id);
            //db.Roads.Remove(road);
            //await db.SaveChangesAsync();
            await ApiHelper.DeleteRoadByID(id);
            return RedirectToAction("Index");
        }

        // GET: Roads/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var road = await ApiHelper.GetRoadById(id);
            if (road == null)
            {
                return HttpNotFound();
            }
            return View(road);
        }

        // GET: Roads/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var road = await ApiHelper.GetRoadById(id);
            if (road == null)
            {
                return HttpNotFound();
            }
            return View(road);
        }

        // POST: Roads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(
               Include =
                   "Id,PlaceId,PlaceType, Jurisdiction,BridgeNum,BridgeWidth,CulvertAndPipeNum,District,From,FunctionalClass,HasUnfinishedSurvey,LaneNum,LastSurveyDate,Name,PavMarkingCondition,PavWidthMax,PavWidthMin,PavWidthTypical,PlaceType,Remarks,ShoulderWidthMax,ShoulderWidthMin,ShoulderWidthTypical,SurfaceType,To,UnpavedShoulderWidth"
               )] Road road)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(road).State = EntityState.Modified;
                //await db.SaveChangesAsync();
                var curUser = UserManager.FindById(User.Identity.GetUserId());
                road.Jurisdiction = curUser.PlaceName;
                road.PlaceType = ApiHelper.GetPlaceById(curUser.PlaceId).Result.Type;
                road.PlaceId = curUser.PlaceId;
                await ApiHelper.EditRoad(road);
                return RedirectToAction("Index");
            }
            
            return RedirectToAction("Index");
        }

        // GET: Roads
        public async Task<ActionResult> Index(int? pageNum)
        {
            if (User.Identity.IsAuthenticated == false)
                return RedirectToAction("Login", "Account");

            var user = UserManager.FindById(User.Identity.GetUserId());
            var roads = await ApiHelper.GetRoadsByPlaceId(user.PlaceId);
            const int countPerPage = 50;
            var pageNumOrDefault = pageNum ?? 1;
            return View(roads.ToPagedList(pageNumOrDefault, countPerPage));
        }
    }
}

Copaces.CityCounty.Website/Controllers/SegmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Copaces.CityCounty.Website.Models;
using Copaces.CityCounty.Website.Models.DataObjects;
using Copaces.CityCounty.Website.Utility;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;

namespace Copaces.CityCounty.Website.Controllers
{
    public class SegmentsController : Controller
    {
        /// <summary>
        /// Application DB context
        /// </summary>
        ApplicationDbContext ApplicationDbContext { get; set; }

        /// <summary>
        /// User manager - attached to application DB context
        /// </summary>
        UserManager<ApplicationUser> UserManager { get; set; }

        private ApplicationUser CurrentUser {
            get {
                return User.Identity.IsAuthenticated ? UserManager.FindById(User.Identity.GetUserId()) : null;
            }
        }

        public SegmentsController()
        {
            ApplicationDbContext = new ApplicationDbContext();
            UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        // GET: Segments
        //public async Task<ActionResult> Index(int? pageNum)
        //{
        //    if (User.Identity.IsAuthenticated == false)
        //        //return View();
        //        return RedirectToAction("Login", "Account");


        //    var segments = await ApiHelper.GetSegmentsByPlace(new Place() {Id = CurrentUser.PlaceId});

        //    var pageNumOrDefault = pageNum ?? 1;
        //    const int countPerPage = 50;

        //    return View(segments.ToPagedList(pageNumOrDefault, countPerPage));
        //}

        public ActionResult Index(string id){
            return RedirectToAction("RoadSegment", "RoadSegment", new { id = id });
        }
        // GET: Segments/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Segment segment = await ApiHelper.GetSegmentById(id);
            if (segment == null)
            {
                return HttpNotFound();
            }
            List<SegmentSurvey> surys = await ApiHelper.GetSegmentSurveysBySegment(segment);
            SegmentSurveyViewModel data = new SegmentSurveyViewModel(surys, segment);
            return View(data);
        }



        public ViewResult Create(string RoadId)
        {
            Segment seg = new Segment();
            seg.RoadId = RoadId;
            return View(seg);
        }


        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var segment = await ApiHelper.GetSegmentById(id);
            if (segment == null)
            {
                return HttpNotFound();
            }
            return View(segment);
        }

        // POST: Roads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            //var road = await db.Roads.FindAsync(id);
            //db.Roads.Remove(road);
            //await db.SaveChangesAsync();
            await ApiHelper.DeleteSegmentByID(id);
            return RedirectToAction("Index");
        }







        // POST: Segments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(
                Include =
                    "From,To,HasCurbOrGutter,Id,RoadId,SequenceId,LaneDirection,LaneNum,Length,Remarks,SampleLocation"
                )] Segment segment)
        {
            if (ModelState.IsValid)
            {
                //db.Segments.Add(segment);
                //await db.SaveChangesAsync();
                //segment.Id = ApiHelper.setSegmentId();
                var curUser = UserManager.FindById(User.Identity.GetUserId());
                //segment.Place = ApiHelper.GetPlaceById(curUser.PlaceId).Result;
                segment.PlaceId = curUser.PlaceId;
                var res = await ApiHelper.GetNextSegmentInventId(curUser.PlaceId);
                segment.InventId = res+1;
                segment.Id = ApiHelper.GetNextRoadId();
                await ApiHelper.CreateSegment(segment);
                return RedirectToAction("RoadSegments", "RoadSegments", new { id = segment.RoadId });
            }
               
            ModelStateErrors(ModelState);           // For debug purpose
            ViewBag.RoadId = new SelectList(await ApiHelper.GetRoadsByPlaceId(CurrentUser.PlaceId), "Id", "District");
            return View(segment);
        }


        public static void ModelStateErrors(ModelStateDictionary modelState)
        {
            var errors = modelState.Where(a => a.Value.Errors.Count > 0)
                .Select(b => new { b.Key, b.Value.Errors })
                .ToArray();

            foreach (var modelStateErrors in errors)
            {
                System.Diagnostics.Debug.WriteLine("...Errored When Binding.", modelStateErrors.Key.ToString());

            }

        }
        // GET: Segments/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Segment segment = await ApiHelper.GetSegmentById(id);
            if (segment == null)
            {
                return HttpNotFound();
            }
            ViewBag.RoadId = new SelectList(await ApiHelper.GetRoadsByPlaceId(CurrentUser.PlaceId), "Id", "District");
            return View(segment);
        }

        // POST: Segments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(
                Include =
                    "Id,From,HasCurbOrGutter,InventId,LaneDirection,LaneNum,Length,PlaceId,Remarks,RoadId,SampleLocation,SequenceId,To"
                )] Segment segment)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(segment).State = EntityState.Modified;
                //await db.SaveChangesAsync();
                var curSegment = ApiHelper.GetSegmentById(segment.Id).Result;
                curSegment.SequenceId = segment.SequenceId;
                curSegment.From = segment.From;
                curSegment.To = segment.To;
                curSegment.LaneDirection = segment.LaneDirection;
                curSegment.LaneNum = segment.LaneNum;
                curSegment.Length = segment.Length;
                curSegment.SampleLocation = segment.SampleLocation;
                curSegment.HasCurbOrGutter = segment.HasCurbOrGutter;
                curSegment.Remarks = segment.Remarks;
                await ApiHelper.EditSegment(curSegment);
                return RedirectToAction("Index");
            }
            //ViewBag.RoadId = new SelectList(await ApiHelper.GetRoadsByPlaceId(CurrentUser.PlaceId), "Id", "District");

            return View(segment);
        }

        // GET: Segment/History/5
        public async Task<ActionResult> History(int? id)
        {
            if (!id.HasValue)
                return View();

            var surveyList = await ApiHelper.GetSegmentSurveysBySegment(new Segment {InventId = id.Value});

            if (surveyList == null || surveyList.Count == 0)
            {
                ViewBag.HasHistory = false;
                return View();
            }
            else
            {
                ViewBag.HasHistory = true;
                var labelList = surveyList.Select(e => e.SegSurveyDate).ToList();
                var dataList = surveyList.Select(e => e.CopacesRating).ToList();
                var chartData = new
                {
                    labels = labelList,
                    datasets = new[]
                    {
                        new
                        {
                            label = "Rating History",
                            fillColor = "rgba(220,220,220,0.2)",
                            strokeColor = "rgba(220,220,220,1)",
                            pointColor = "rgba(220,220,220,1)",
                            pointStrokeColor = "#fff",
                            pointHighlightFill = "#fff",
                            pointHighlightStroke = "rgba(220,220,220,1)",
                            data = dataList
                        }
                    }
                }; 
                return View(chartData);
            }
        }

        //public async Task<ActionResult> Search(SegmentSearchViewModel searchViewModel)
        public async Task<ActionResult> Search(SegmentSearchViewModel searchViewModel)
        {
            if (User.Identity.IsAuthenticated == false)
                return View();

            if (!searchViewModel.IsEmptyQuery)
                searchViewModel.Result = await ApiHelper.SearchSegments(
                    from: searchViewModel.From,
                    to: searchViewModel.To,
                    roadId: searchViewModel.RoadId,
                    placeId: CurrentUser.PlaceId);

            var roads = await ApiHelper.GetRoadsByPlaceId(CurrentUser.PlaceId);
            roads.Insert(0, new Road { Id = null, Name = string.Empty });

Copaces.CityCounty.Website/Views/Roads/Create.cshtml
@model Copaces.CityCounty.Website.Models.DataObjects.Road

@{
    ViewBag.Title = "Create New Road";
}
    <h2 >Create New Road</h2>  




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div id="backtoList" align="right">
        @Html.ActionLink("Back to List", "Index", "Roads", new { @class = "btn btn-info" })
    </div>
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })           
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.To, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.BridgeNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BridgeNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BridgeNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BridgeWidth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BridgeWidth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BridgeWidth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CulvertAndPipeNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CulvertAndPipeNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CulvertAndPipeNum, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.FunctionalClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FunctionalClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FunctionalClass, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.LaneNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LaneNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LaneNum, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            @Html.LabelFor(model => model.PavMarkingCondition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PavMarkingCondition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PavMarkingCondition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PavWidthMax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PavWidthMax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PavWidthMax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PavWidthMin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PavWidthMin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PavWidthMin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PavWidthTypical, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PavWidthTypical, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PavWidthTypical, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            @Html.LabelFor(model => model.ShoulderWidthMax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShoulderWidthMax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShoulderWidthMax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShoulderWidthMin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShoulderWidthMin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShoulderWidthMin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShoulderWidthTypical, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShoulderWidthTypical, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShoulderWidthTypical, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurfaceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SurfaceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SurfaceType, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.UnpavedShoulderWidth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnpavedShoulderWidth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnpavedShoulderWidth, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Copaces.CityCounty.Website/Views/Roads/Index.cshtml
@model PagedList.IPagedList<Copaces.CityCounty.Website.Models.DataObjects.Road>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "Roads";
}


<div class="row">
    <div class="col-lg-12">
        <div class="main-box clearfix">
            <header class="main-box page-header clearfix">
                <div class="filter-block pull-left"><h2>Roads</h2></div>
                <div class="filter-block pull-right pull-down down">
                    <div class="form-group pull-leftleft">
                        <a href="@Url.Action("Create")" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-edit"></i>&nbsp; Create New<span class="sr-only"> </span></a>
                        <a href="@Url.Action("Search", "Segments")" class="btn btn-info btn-sm"><i class="glyphicon glyphicon-search"></i>&nbsp; Search Survey Reports<span class="sr-only"> </span></a>
                    </div>
                </div>
            </header>

            <div class="row">
                <div class="col-lg-12">
                    <div class="main-box clearfix">
                       <div class="main-box-body clearfix">
                            <div class="table-responsive clearfix">
                                <table id="table-example" class="table table-hover table-striped sortable">
                                    <thead>
                                        <tr>
                                            <th><span>Road Name</span></th>
                                            <th><span>Jurisdiction</span></th>
                                            <th><span>From</span></th>
                                            <th><span>To</span></th>
                                            <th><span>Survey Status</span></th>
                                            <th><span>Last Survey Date</span></th>
                                            <th>&nbsp;</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            @foreach (var item in Model)
                                                {
                                                <tr>
                                                    <td>@Html.ActionLink(item.Name, "RoadSegments", "RoadSegments", new { id = item.Id }, null)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.Jurisdiction)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.From)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.To)</td>
                                                    @if ((item.HasUnfinishedSurvey == false) && (item.LastSurveyDate != null))
                                                    {
                                                        <td><span class="label label-success">Complete</span></td>
                                                    }
                                                    else if ((item.HasUnfinishedSurvey == false) && (item.LastSurveyDate == null))
                                                    {
                                                        <td><span class="label label-danger">Not Started</span></td>
                                                    }
                                                    else if ((item.HasUnfinishedSurvey == true) && (item.LastSurveyDate != null))
                                                    {
                                                        <td><span class="label label-warning">Incomplete</span></td>
                                                    }
                                                    <td>@Html.DisplayFor(modelItem => item.LastSurveyDate)</td>
                                                    <td>
                                                        <a href="@Url.Action("Edit", "Roads", new { id = item.Id })" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-pencil"></i>&nbsp; Edit<span class="sr-only"> </span></a>
                                                        <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i>&nbsp; Delete<span class="sr-only"></span></a>
                                                    </td>
                                                </tr>
                                                }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, pageNum => Url.Action("Index",
    new { placeId = ViewBag.PlaceId, pageNum }))